import { library } from "@fortawesome/fontawesome-svg-core";
import {
	faSun as fasSun,
	faMoon as fasMoon,
	faCircle as fasCircle,
	faBars as fasBars,
	faPlus as fasPlus,
	faMinus as fasMinus,
	faStar as fasStar,
	faSlash as fasSlash,
	faLock as fasLock,
	faPen as fasPen,
	faFlag as fasFlag,
	faCheck as fasCheck,
	faChevronRight as fasChevronRight,
	faChevronLeft as fasChevronLeft,
	faGavel as fasGavel,
	faExclamationTriangle as fasExclamationTriangle,
	faExclamation as fasExclamation,
	faExternalLinkAlt as fasExternalLinkAlt,
	faCalendarAlt as fasCalendarAlt,
	faPalette as fasPalette,
	faCube as fasCube,
	faGear as fasGear,
	faUsersCog as fasUsersCog,
	faEllipsisH as fasEllipsisH,
	faEllipsisV as fasEllipsisV,
	faColumns as fasColumns,
	faTrash as fasTrash,
	faTimes as fasTimes,
	faSearch as fasSearch,
	faInbox as fasInbox,
	faUserEdit as fasUserEdit,
	faReply as fasReply,
	faArrowLeft as fasArrowLeft,
	faObjectGroup as fasObjectGroup,
	faLayerGroup as fasLayerGroup,
	faEyeSlash as fasEyeSlash,
	faTag as fasTag,
	faLanguage as fasLanguage,
} from "@fortawesome/free-solid-svg-icons";
import { faCircleCheck as farCircleCheck } from "@fortawesome/free-regular-svg-icons";
import {
	faChrome as fabChrome,
	faFirefox as fabFirefox,
	faEdge as fabEdge,
	faOpera as fabOpera,
	faTwitter as fabTwitter,
	faGithub as fabGithub,
	faTwitch as fabTwitch,
	faYoutube as fabYoutube,
	faDiscord as fabDiscord,
} from "@fortawesome/free-brands-svg-icons";

library.add(
	fasSun,
	fasMoon,
	fabChrome,
	fabFirefox,
	fabEdge,
	fabOpera,
	fabTwitter,
	fabGithub,
	fasCircle,
	fasBars,
	fasPlus,
	fasMinus,
	fabTwitch,
	fabYoutube,
	fabDiscord,
	fasStar,
	fasCheck,
	farCircleCheck,
	fasSlash,
	fasLock,
	fasPen,
	fasFlag,
	fasSearch,
	fasChevronRight,
	fasChevronLeft,
	fasGavel,
	fasExclamationTriangle,
	fasExclamation,
	fasExternalLinkAlt,
	fasCalendarAlt,
	fasPalette,
	fasCube,
	fasGear,
	fasUsersCog,
	fasEllipsisH,
	fasEllipsisV,
	fasColumns,
	fasTrash,
	fasTimes,
	fasSearch,
	fasInbox,
	fasUserEdit,
	fasReply,
	fasArrowLeft,
	fasObjectGroup,
	fasLayerGroup,
	fasEyeSlash,
	fasTag,
	fasLanguage,
);
